import {notFound} from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import Shell from '../../../components/Shell';
import {Contact} from '../../../components/Sections';
import {projects} from '../../../components/data';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);return {title:`${p?.name||'Project'} — Muhammad Luqman`,description:p?.description,alternates:{canonical:`/work/${slug}`}}}
export default async function CaseStudy({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();return <Shell><section className="case-hero"><Link href="/work" className="mono">← SELECTED WORK</Link><h1>{p.name}</h1><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-links">{p.live&&<a href={p.live} target="_blank" rel="noreferrer">VIEW LIVE ↗</a>}<a href={p.repo} target="_blank" rel="noreferrer">INSPECT SOURCE ↗</a></div></section><div className="case-image"><Image src={p.image} width={1440} height={960} sizes="100vw" preload alt={`${p.name} interface`}/></div><section className="case-content"><aside className="case-aside"><span className="mono">ENGINEERING CASE STUDY / {p.number}</span><p>This study documents the linked repository and its implementation. Explore the source for the complete build history and contributors.</p></aside><div>{[['01','The problem',p.problem],['02','The architecture',p.architecture],['03','The execution',p.execution],['04','The result',p.result]].map(([n,title,copy])=><article className="case-block" key={n}><span className="mono">CHAPTER / {n}</span><h2>{title}</h2><p>{copy}</p></article>)}</div></section><div className="case-back"><Link className="button button-white" href="/contact">HAVE A SIMILAR IDEA? <span>↗</span></Link></div><Contact/></Shell>}
