export const articles=[
 {slug:'portfolio',title:'How to evaluate a full stack developer portfolio',description:'A practical way to inspect frontend work, backend integrations and repository evidence before choosing a developer.',sections:[
 {heading:'Start with a user task',paragraphs:['A developer portfolio is useful when it helps you understand how someone approaches a real product. Attractive screens are a good starting point, but the stronger question is what a visitor can actually do with the application. Choose one action and follow it from the interface to its result.','For a dashboard, that might mean finding a piece of information and checking where it came from. For a project enquiry, it means entering the details, understanding the next step and recovering from an incomplete form. This gives you a clearer picture than a long list of technologies.']},
 {heading:'Look for evidence across the whole system',paragraphs:['Full stack development connects the interface, application logic, APIs and data. A portfolio should make those connections inspectable. Look for a working application, a repository where one is available and a concise explanation of the problem being addressed.','Muhammad Luqman’s portfolio links Circle Arc Net and Circle Portfolio Agent as work examples. It also separates Xroga as current development and labels external repositories as references. That distinction matters. A reference can explain an influence, while project evidence should explain the developer’s own contribution.']},
 {heading:'Ask questions that reveal practical judgement',paragraphs:['Ask what happens when a request fails, how sensitive configuration is handled and what the user sees while waiting. Ask which part of the product was deliberately kept simple. These questions reveal how a developer balances scope, clarity and reliability.','You do not need to read every line of code to make a useful assessment. A developer who can explain a feature, show its implementation and discuss its limits gives you something concrete to review.']},
 {heading:'Use the portfolio to begin a focused conversation',paragraphs:['Bring a specific product goal to the first conversation. Describe who will use it, the main task they need to complete and what already exists. A useful enquiry gives the developer enough context to propose a first release rather than guess at a large collection of features.','Muhammad Luqman, also referred to as M Luqman or Luqman, presents his developer work at LuqmanDev.top. Explore the selected work, then use the contact form to describe your project. The budget field is optional. Clear requirements are a better starting point than an impressive sounding specification.']}]},
 {slug:'mvp',title:'Planning an MVP that can grow into a real product',description:'How to turn an early SaaS or web application idea into a focused first release with clear user flows and connected infrastructure.',sections:[
 {heading:'Define one valuable outcome',paragraphs:['Turning ideas into working products starts with a clear outcome. An MVP becomes difficult when it is treated as a smaller version of every feature you can imagine. Start with a person and a problem instead. What should that person be able to accomplish after using the first release?','For example, a booking application might initially need to help a customer choose a slot and receive confirmation. A marketplace might first need a clear path from a listing to a useful enquiry. These are hypothetical examples, but the principle is the same: make one important journey work.']},
 {heading:'Map the product before selecting tools',paragraphs:['For a tech company or an AI company planning a new web product, the same approach applies. Write down the steps in that journey. Identify the information needed at each step and decide which actions require an account, a server request or a notification. This connects product design to the application architecture.','React and Next.js can support a modern interface, but a framework name does not replace a release plan. The useful decision is how the frontend, APIs, authentication and data will work together for the specific product.']},
 {heading:'Keep the first release small without hiding the hard parts',paragraphs:['A focused release still needs clear loading states, validation and a usable experience on a phone. These details affect whether someone can finish the task at all. Treat them as part of the product rather than decoration added at the end.','Some advanced features can wait. A complex reporting system, a second subscription tier or a large automation catalogue may not be necessary to test the first user journey. Document those choices so the scope remains understandable.']},
 {heading:'Build a foundation you can inspect',paragraphs:['Keep configuration separate from application content. Make the data model understandable and describe important integrations. These habits make later changes easier to discuss, even when the first release is deliberately modest.','Muhammad Luqman’s services include MVP development, SaaS products and full stack web applications. His stated process moves through discovery, structure, design, engineering, validation and launch. A useful project brief can follow the same sequence: explain the problem, agree on the first outcome and decide what should be reviewed before release.']}]},
 {slug:'apis',title:'What reliable API integration needs beyond a successful request',description:'A clear checklist for API development, failure handling, data boundaries and useful feedback in a full stack application.',sections:[
 {heading:'A successful response is only one case',paragraphs:['Connecting an API is easy to demonstrate when the service responds quickly and returns exactly what the application expects. A reliable product also considers missing data, slow responses and requests that fail.','The interface should tell the user what is happening. It should distinguish between an empty result and an unavailable service. Those situations may look similar on a screen, but they require different explanations and different next steps.']},
 {heading:'Define the boundary between systems',paragraphs:['Decide what information the application sends and which fields it needs in return. Validate data where it enters the system instead of assuming that every response will remain unchanged. Keep the interface independent of unnecessary details from an external provider.','Sensitive credentials belong in a protected server environment. A browser interface should receive the data it needs to show the feature, not private configuration intended for a backend integration.']},
 {heading:'Design recovery around the action',paragraphs:['A search request and a payment request do not have the same consequences. Before adding a retry, consider whether repeating the action could create duplicate work. For actions that change data, decide how the application recognises an operation that has already been handled.','Webhooks need similar care. A notification can arrive more than once or arrive after another event. The receiving system should make its assumptions clear and keep enough information to investigate a problem.']},
 {heading:'Make the integration inspectable',paragraphs:['Record useful error context without exposing secrets. Describe the expected request and response. Test a missing field and a service failure as well as the successful path. These practices help the next developer understand the boundary and help a client judge whether the feature is ready.','The Circle Portfolio Agent entry in Muhammad Luqman’s portfolio describes a modular API layer connecting market signals and cross chain workflows. Readers can inspect the linked repository for implementation evidence. For a new integration project, begin with the user action, the external service and the result the application needs to produce.']}]},
 {slug:'motion',title:'Designing a 3D developer portfolio that remains easy to use',description:'How a moving portfolio can balance visual identity with readable text, mobile layouts, accessible controls and clear project evidence.',sections:[
 {heading:'Give the content a clear priority',paragraphs:['A moving portfolio has two jobs. It needs to express the developer’s visual identity and help a visitor understand the work. The second job should remain clear while the first creates interest.','Put the name, role and important actions in readable foreground layers. Treat a particle scene or a 3D object as a background experience. The visitor should not need to decode an animation to find the projects or contact details.']},
 {heading:'Use motion to explain the journey',paragraphs:['Movement is most useful when it tells a visitor where they are or confirms an interaction. A project transition can introduce the next build. A small hover response can show that a card is interactive. Continuous decoration should remain subtle enough to leave the text readable.','LuqmanDev.top uses a neural background in the hero and different visual treatments for projects and services. Contact actions scroll to the enquiry form on the current page. This keeps the path to a conversation connected to the content the visitor was already reading.']},
 {heading:'Design the phone experience separately',paragraphs:['A desktop composition often depends on width and a large visible area. Shrinking it unchanged can make a phone page difficult to use. Stack the portrait and introduction, give controls enough space and allow paragraphs to flow naturally.','The mobile layout of Muhammad Luqman’s portfolio uses stacked project and service content, readable form fields and a compact contact control. Its process steps appear in a regular scrolling layout rather than requiring the visitor to navigate a tall pinned panel.']},
 {heading:'Keep an accessible fallback',paragraphs:['A portfolio should remain understandable when decorative graphics cannot run. Reduced motion preferences should also preserve the information and actions. Visual ambition is easier to trust when the developer has considered those limits.','A good review looks beyond the first screen. Read a project description, inspect a source link, open the contact form and try the same tasks at a narrow width. A distinctive portfolio works best when it remains a useful website throughout that journey.']}]}
];
