export const email = 'moeed.zio1315@gmail.com';
export const github = 'https://github.com/mluqman555';
export const projects = [
 {slug:'circle-arc',number:'01',name:'Circle Arc Net',category:'WEB3 / PRODUCT ENGINEERING',description:'A command centre for portfolio analysis, agent workflows and cross-chain USDC execution.',tags:['Next.js','TypeScript','Circle','APIs'],repo:'https://github.com/mluqman555/Circle-Arc-Net',live:'https://circle-arc-net.vercel.app/',image:'/projects/circle-arc.webp',accent:'blue',problem:'Make portfolio information and cross-chain execution accessible from one connected application.',architecture:'A Next.js App Router frontend connects to server-side route handlers for market data, portfolio analysis, execution planning and Circle integrations. React Query manages client data; wagmi and viem support wallet interactions.',execution:'The public repository contains dedicated command, portfolio, execution and agent screens, typed API routes, a health endpoint and Vercel configuration. External credentials stay on the server.',result:'An inspectable application with a published demo and source code. Wallet operations and live data depend on the connected services and configured credentials; no trading or financial-performance claims are made.'},
 {slug:'circle-agent',number:'02',name:'Circle Portfolio Agent',category:'BACKEND / SYSTEM INTEGRATION',description:'Market signals, adaptive allocation and cross-chain workflows connected through a modular API layer.',tags:['React','Node.js','REST APIs','Circle'],repo:'https://github.com/mluqman555/Circle',live:null,image:'/projects/circle-agent.svg',accent:'green',problem:'Organise market intelligence, portfolio information and execution services into a maintainable application.',architecture:'A React/Vite interface works with Node.js services and Vercel API handlers. The code separates market signals, rebalancing, portfolio data, wallet management and cross-chain operations.',execution:'The repository includes market-data integrations, allocation logic, API endpoints and a separate frontend. Its architecture makes each integration inspectable and keeps service credentials in environment variables.',result:'A source-available engineering project demonstrating connected frontend and backend modules. This case study describes the repository; it does not imply audited autonomous trading or verified commercial outcomes.'},
 {slug:'luqman-portfolio',number:'03',name:'Luqman / Developer OS',category:'CREATIVE DEVELOPMENT / INTERACTIVE WEB',description:'The portfolio you are exploring. A fast, cinematic development environment with a connected 3D universe.',tags:['Next.js','TypeScript','WebGL','Canvas'],repo:'https://github.com/mluqman555/portfolio',live:'https://www.luqmandev.top',image:'/projects/portfolio.svg',accent:'red',problem:'Translate a detailed visual brief into a readable, responsive portfolio that balances expressive motion with practical navigation.',architecture:'Server-rendered Next.js pages carry the content. Small client components power a pooled code cursor, a projected wireframe hero and a lazy-loaded single WebGL development universe.',execution:'Local fonts, responsive screenshots, intersection-based animation scheduling, keyboard controls and reduced-motion fallbacks keep the experience usable across devices.',result:'A deployed English portfolio with inspectable source, dedicated case studies and a project enquiry flow. Performance is measured in testing; real-user Core Web Vitals require production traffic.'}
] as const;
export const skills = [
 ['React','Interfaces composed around reusable components and clear state.','FRONTEND'],['Next.js','Full-stack React applications, routing, server rendering, API integration and production deployment.','FULL-STACK'],['TypeScript','Typed interfaces, predictable data contracts and maintainable application logic.','LANGUAGE'],['Node.js','Server-side application logic, API handlers and connected services.','BACKEND'],['Database','Data modelling, SQL and persistent application state.','DATA'],['APIs','REST endpoints, webhooks and reliable third-party integrations.','INTEGRATION'],['Git','Version control, reviewable changes and a clear build history.','WORKFLOW'],['Cloud','Production builds, Vercel delivery and deployment configuration.','DELIVERY'],['AI','Practical model integrations and automation connected to product functions.','AUTOMATION']
] as const;
export const expertise = [
 ['Core languages','TypeScript · JavaScript · SQL · HTML · CSS','01'],['Frontend engineering','React · Next.js · Responsive UI · Dashboards · Interactive experiences','02'],['Backend & data','Node.js · REST APIs · Authentication · Webhooks · Data modelling','03'],['Product engineering','User flows · Product structure · UI/UX · Rapid prototyping · MVP development','04'],['AI & automation','LLM integrations · Workflow automation · AI-assisted applications · Developer tooling','05'],['Delivery','Git · GitHub · Testing · Debugging · Deployment · Vercel · Iteration','06']
];
export const services = [
 ['Full-Stack Web Applications','Production-ready applications connecting polished interfaces to real backend systems.','01'],['SaaS Products','Authentication, dashboards, roles, subscriptions, data workflows and product infrastructure.','02'],['Frontend Experiences','Fast, responsive and visually distinctive web experiences.','03'],['Backend & API Development','Application logic, integrations, databases, authentication, APIs and webhooks.','04'],['AI & Automation','Practical AI integrations and automated workflows connected to real product functions.','05'],['MVP Development','Turning an early concept into a focused, testable and deployable first product.','06']
];
