export const email = 'mluqman246810@gmail.com';
export const github = 'https://github.com/mluqman555';
export const projects = [
 {slug:'circle-arc',number:'01',name:'Circle Arc Net',category:'WEB3 / PRODUCT ENGINEERING',description:'A command centre for portfolio analysis, agent workflows and cross-chain USDC execution.',tags:['Next.js','TypeScript','Circle','APIs'],repo:'https://github.com/mluqman555/Circle-Arc-Net',live:'https://circle-arc-net.vercel.app/',image:'/projects/circle-arc.webp',accent:'blue',problem:'Make portfolio information and cross-chain execution accessible from one connected application.',architecture:'A Next.js App Router frontend connects to server-side route handlers for market data, portfolio analysis, execution planning and Circle integrations. React Query manages client data; wagmi and viem support wallet interactions.',execution:'The public repository contains dedicated command, portfolio, execution and agent screens, typed API routes, a health endpoint and Vercel configuration. External credentials stay on the server.',result:'An inspectable application with a published demo and source code. Wallet operations and live data depend on the connected services and configured credentials; no trading or financial-performance claims are made.'},
 {slug:'circle-agent',number:'02',name:'Circle Portfolio Agent',category:'BACKEND / SYSTEM INTEGRATION',description:'Market signals, adaptive allocation and cross-chain workflows connected through a modular API layer.',tags:['React','Node.js','REST APIs','Circle'],repo:'https://github.com/mluqman555/Circle',live:null,image:'/projects/circle-agent.svg',accent:'green',problem:'Organise market intelligence, portfolio information and execution services into a maintainable application.',architecture:'A React/Vite interface works with Node.js services and Vercel API handlers. The code separates market signals, rebalancing, portfolio data, wallet management and cross-chain operations.',execution:'The repository includes market-data integrations, allocation logic, API endpoints and a separate frontend. Its architecture makes each integration inspectable and keeps service credentials in environment variables.',result:'A source-available engineering project demonstrating connected frontend and backend modules. This case study describes the repository; it does not imply audited autonomous trading or verified commercial outcomes.'},
] as const;
export const skills = [
 ['React','Interfaces composed around reusable components and clear state.','FRONTEND'],['Next.js','Full-stack React applications, routing, server rendering, API integration and production deployment.','FULL-STACK'],['TypeScript','Typed interfaces, predictable data contracts and maintainable application logic.','LANGUAGE'],['Node.js','Server-side application logic, API handlers and connected services.','BACKEND'],['Database','Data modelling, SQL and persistent application state.','DATA'],['APIs','REST endpoints, webhooks and reliable third-party integrations.','INTEGRATION'],['Git','Version control, reviewable changes and a clear build history.','WORKFLOW'],['Cloud','Production builds, Vercel delivery and deployment configuration.','DELIVERY'],['AI','Practical model integrations and automation connected to product functions.','AUTOMATION']
] as const;
export const expertise = [
 ['Core languages','TypeScript · JavaScript · SQL · HTML · CSS','01'],['Frontend engineering','React · Next.js · Responsive UI · Dashboards · Interactive experiences','02'],['Backend & data','Node.js · REST APIs · Authentication · Webhooks · Data modelling','03'],['Product engineering','User flows · Product structure · UI/UX · Rapid prototyping · MVP development','04'],['AI & automation','LLM integrations · Workflow automation · AI-assisted applications · Developer tooling','05'],['Delivery','Git · GitHub · Testing · Debugging · Deployment · Vercel · Iteration','06']
];
export const services = [
 ['Full-Stack Web Applications','Custom websites and full-stack platforms connecting intuitive interfaces to dependable application logic, data and Web3 integrations.','01'],['SaaS Products','Authentication, dashboards, roles, subscriptions, data workflows and product infrastructure.','02'],['Frontend Experiences','Responsive websites and interactive UI/UX, with clear user flows, performance and organic search optimisation.','03'],['Backend & API Development','Application logic, integrations, databases, authentication, APIs and webhooks.','04'],['AI & Automation','Advanced AI systems, LLM integrations, AI bots, workflow automations and practical tools and software connected to real product functions.','05'],['MVP Development','Turning an early concept into a focused, testable and deployable first product.','06']
];

export const capabilities = ["Custom Websites","Full-Stack Custom Platforms","SaaS Products","Advanced AI Systems","AI Bots","Tools & Software","Robust APIs & Integrations","Workflow Automations","Web3 Systems","Intuitive UI/UX","Organic Search Optimisation"] as const;
export const universeGroups = [{"name":"Languages & interface","items":["JavaScript","TypeScript","HTML","CSS","React","Next.js","Responsive UI","UI/UX","Routing","Server Rendering","Component Systems","Interactive Experiences"]},{"name":"Backend & data","items":["Node.js","REST APIs","API Integration","Webhooks","Authentication","SQL","Databases","Data Modelling","Application Logic"]},{"name":"AI, automation & Web3","items":["AI","LLM Integrations","Advanced AI Systems","AI Bots","Workflow Automation","AI-Assisted Applications","Developer Tooling","Web3","Circle","Cross-chain Integrations"]},{"name":"Product & delivery","items":["Custom Websites","Full-Stack Platforms","SaaS","MVP Development","Product Structure","Rapid Prototyping","User Flows","Git","GitHub","Testing","Debugging","Vercel","Cloud Delivery","Deployment","Iteration","Organic Search Optimisation"]}] as const;
export const architectureLayers = [["Interface","Websites · Responsive UI · UI/UX · React · Next.js"],["Application","Full-Stack Platforms · SaaS · Product Logic"],["Backend","Node.js · REST APIs · Authentication · Webhooks"],["Data","Databases · SQL · Data Modelling · Persistent State"],["AI","Advanced AI Systems · LLM Integrations · AI Bots"],["Automation","Workflow Automation · Tools · Software Systems"],["Web3","Web3 Integrations · Circle · Cross-chain Services"],["Delivery","Testing · Debugging · Git · GitHub · Vercel · Deployment"],["Discovery","Product Structure · MVPs · User Flows · Organic Search Optimisation"]] as const;
