'use client';
import {useEffect,useRef} from 'react';
const smooth=(a:number,b:number,x:number)=>{const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)};
export default function HeroFallback({reason}:{reason:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current,host=canvas?.closest<HTMLElement>('.cinematic-hero');if(!canvas||!host)return;const ctx=canvas.getContext('2d');if(!ctx)return;const mobile=innerWidth<700,count=mobile?650:1200;let seed=42;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const points=Array.from({length:count},(_,i)=>{const u=rand()*Math.PI*2,v=rand()*Math.PI*2,r=Math.pow(rand(),.2),a=u+.3*Math.sin(v*2),lobe=i%3,b=i%9,t=rand(),sign=b%2?1:-1;return {cx:((Math.cos(a)*(.75+.22*Math.sin(u*3))+.25*Math.cos(v))*r+(lobe===0?-.34:lobe===1?.28:0))*1.25,cy:(Math.sin(a)*(.85+.1*Math.cos(u*2))+.25*Math.sin(v))*r*.9,cz:Math.sin(v)*.48*r,nx:sign*(.12+t*1.62)+(rand()-.5)*.14,ny:Math.sin(t*2.7+b*.7)*(.15+t*.78)+(rand()-.5)*.12,nz:Math.cos(t*3.4+b)*.37,sx:(rand()-.5)*6,sy:(rand()-.5)*4.5,sz:(rand()-.5)*5,seed:rand(),size:1.1+rand()*2.1,color:rand(),x:0,y:0,z:0,influence:0}});
 let width=1,height=1,time=0,previous=0,frame=0,visible=true,progress=0,px=-10,py=-10,tx=-10,ty=-10,dirty=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const resize=()=>{const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const dpr=Math.min(devicePixelRatio,mobile?1:1.5);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);dirty=true};const move=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();tx=e.clientX-r.left;ty=e.clientY-r.top;dirty=true};const leave=()=>{tx=-10;ty=-10;dirty=true};
 const render=(now:number)=>{if(visible&&!document.hidden&&(now-previous>=32||dirty)){const dt=Math.min((now-previous)/1000,.06)||.016;previous=now;const active=!reduced.matches&&host.dataset.paused!=='true';if(active)time+=dt;const target=reduced.matches?.28:parseFloat(host.dataset.sceneProgress||'0');progress+=(target-progress)*(1-Math.exp(-dt*8));px+=(tx-px)*(1-Math.exp(-dt*6));py+=(ty-py)*(1-Math.exp(-dt*6));if(active||dirty||Math.abs(progress-target)>.001){dirty=false;ctx.clearRect(0,0,width,height);const branch=smooth(.05,.35,progress),dissolve=smooth(.58,1,progress),pan=smooth(.08,.34,progress),scale=height*.245;
 for(const p of points){let x=p.cx+(p.nx-p.cx)*branch,y=p.cy+(p.ny-p.cy)*branch,z=p.cz+(p.nz-p.cz)*branch;x+=(p.sx-x)*dissolve*.85;y+=(p.sy-y)*dissolve*.85;z+=(p.sz-z)*dissolve*.85;x+=Math.sin(time*.3+p.seed*15)*.025;y+=Math.cos(time*.25+p.seed*19)*.025;const a=.15+Math.sin(time*.1)*.035,xr=x*Math.cos(a)+z*Math.sin(a),zr=-x*Math.sin(a)+z*Math.cos(a),perspective=5.9/(5.9-zr);p.x=width*.5+(xr+pan*(mobile?0:1.15))*scale*perspective;p.y=height*.5-(y-pan*.08)*scale*perspective;p.z=zr;const targetInfluence=active?Math.max(0,1-Math.hypot(p.x-px,p.y-py)/(height*.16))**2:0;p.influence+=(targetInfluence-p.influence)*(1-Math.exp(-dt*6))}
 points.sort((a,b)=>a.z-b.z);
 for(const p of points){const size=p.size*(1+p.influence*2.4)*(1+p.z*.12)*(mobile?.8:1),a=p.seed*23+time*(.04+p.seed*.07),c=Math.cos(a),s=Math.sin(a);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.globalAlpha=(.42+(p.z+.6)*.18)*(1-dissolve*.4);const colors=p.color<.66?['#e0dfed','#8e8ca6','#b6b4c6']:p.color<.81?['#bda6df','#715b98','#9780b9']:p.color<.93?['#dabf8b','#8c663a','#b98f56']:['#abd5cf','#477a78','#71aaa5'];ctx.fillStyle=colors[0];ctx.beginPath();ctx.moveTo(0,-size*1.6);ctx.lineTo(size*(.9+Math.abs(c)*.4),size*.5);ctx.lineTo(-size*.12,0);ctx.closePath();ctx.fill();ctx.fillStyle=colors[1];ctx.beginPath();ctx.moveTo(0,-size*1.6);ctx.lineTo(-size*(.8+Math.abs(s)*.4),size*.65);ctx.lineTo(-size*.12,0);ctx.closePath();ctx.fill();ctx.fillStyle=colors[2];ctx.beginPath();ctx.moveTo(-size*(.8+Math.abs(s)*.4),size*.65);ctx.lineTo(size*(.9+Math.abs(c)*.4),size*.5);ctx.lineTo(-size*.12,0);ctx.closePath();ctx.fill();ctx.restore()}ctx.globalAlpha=1;canvas.dataset.ready='true'}}frame=requestAnimationFrame(render)};
 const ro=new ResizeObserver(resize);ro.observe(canvas);const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;dirty=true});io.observe(host);host.addEventListener('pointermove',move,{passive:true});host.addEventListener('pointerleave',leave);resize();frame=requestAnimationFrame(render);return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();host.removeEventListener('pointermove',move);host.removeEventListener('pointerleave',leave)}},[]);return <canvas ref={ref} className="hero-fallback-canvas" data-reason={reason} aria-hidden="true"/>}
