'use client';
import {useEffect,useRef,useState} from 'react';
export default function Hero(){
 const canvasRef=useRef<HTMLCanvasElement>(null),pauseRef=useRef(false);const [paused,setPaused]=useState(false);
 useEffect(()=>{pauseRef.current=paused},[paused]);
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const preference=matchMedia('(prefers-reduced-motion: reduce)');let width=0,height=0,frame=0,visible=true,last=0,time=0,dirty=true;const pointer={x:0,y:0};
 const particles=Array.from({length:1100},(_,i)=>({u:(i/1100)*Math.PI*2,v:((i*137.508)%360)/180*Math.PI,seed:(i*17.13)%1,size:1.5+(i%5)*.45,color:i%4,x:0,y:0,z:0}));
 const resize=()=>{dirty=true;const box=canvas.getBoundingClientRect();width=box.width;height=box.height;const dpr=Math.min(devicePixelRatio,1.5);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};
 const draw=(now:number)=>{const elapsed=last?Math.min(now-last,60):0;if(visible&&!document.hidden&&now-last>=32&&(dirty||(!preference.matches&&!pauseRef.current))){last=now;dirty=false;if(!preference.matches&&!pauseRef.current)time+=elapsed*.00022;ctx.clearRect(0,0,width,height);const scale=Math.min(width*.38,height*.52),morph=(Math.sin(time*.45)+1)/2,rotation=time*.34+pointer.x*.13;for(const p of particles){const radius=.69+.18*Math.cos(p.v*3+p.u*2+time*.45);const twist=p.u*1.5+time*.27;const x=Math.cos(p.u)*radius+Math.cos(p.v+twist)*.22;const y=Math.sin(p.u)*radius*.83+Math.sin(p.v+twist)*.18;const z=Math.sin(p.v+twist)*.33+Math.sin(p.u*3+time)*.16;const ribbonX=Math.cos(p.u)*(.6+.2*Math.cos(p.v)),ribbonY=Math.sin(p.u*2+time*.3)*.43+Math.sin(p.v)*.16;const xx=x*(1-morph*.55)+ribbonX*morph*.55,yy=y*(1-morph*.55)+ribbonY*morph*.55;const xr=xx*Math.cos(rotation)-z*Math.sin(rotation),zr=xx*Math.sin(rotation)+z*Math.cos(rotation),yr=yy*Math.cos(.25+pointer.y*.08)-zr*Math.sin(.25+pointer.y*.08);const perspective=2.8/(2.8-zr);p.x=width*.5+xr*scale*perspective;p.y=height*.49+yr*scale*perspective;p.z=zr}particles.sort((a,b)=>a.z-b.z);
 for(const p of particles){const size=p.size*(1.2+p.z*.5)*(width<600?.8:1);const center=Math.abs(p.x-width*.5)<width*.3&&p.y>height*.2&&p.y<height*.77;ctx.globalAlpha=(.27+(p.z+.6)*.3)*(center?.2:.85);ctx.fillStyle=['#087f64','#235fd4','#d97721','#7c8c9e'][p.color];ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.u+time*.18);ctx.beginPath();ctx.moveTo(0,-size*1.5);ctx.lineTo(size*1.1,size);ctx.lineTo(-size*1.1,size);ctx.closePath();ctx.fill();ctx.restore()}
 ctx.globalAlpha=.45;for(let i=0;i<12;i++){const a=i*Math.PI*2/12+time*.12,x=width*.5+Math.cos(a)*scale*1.12,y=height*.5+Math.sin(a)*scale*.9,s=8+i%3*5;ctx.strokeStyle=['#168660','#2566c4','#da7928'][i%3];ctx.lineWidth=1;ctx.save();ctx.translate(x,y);ctx.rotate(a+time*.25);ctx.beginPath();ctx.moveTo(0,-s);ctx.lineTo(s*.86,s*.5);ctx.lineTo(-s*.86,s*.5);ctx.closePath();ctx.stroke();ctx.restore()}ctx.globalAlpha=1}
 frame=requestAnimationFrame(draw)};
 const move=(e:PointerEvent)=>{if(preference.matches||pauseRef.current)return;dirty=true;pointer.x=(e.clientX/innerWidth-.5);pointer.y=(e.clientY/innerHeight-.5)};const ro=new ResizeObserver(resize);ro.observe(canvas);const io=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting});io.observe(canvas);addEventListener('pointermove',move,{passive:true});resize();frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();removeEventListener('pointermove',move)}},[]);
 return <><canvas className="hero-particle-canvas" ref={canvasRef} aria-hidden="true"/><button className="hero-motion-toggle mono" onClick={()=>setPaused(v=>!v)} aria-pressed={paused}>{paused?'RESUME HERO MOTION':'PAUSE HERO MOTION'}</button></>
}
