'use client';
import {useEffect,useRef} from 'react';
import {capabilities} from './data';
import IdentityCard from './IdentityCard';
import Link from 'next/link';
import dynamic from 'next/dynamic';
const Core=dynamic(()=>import('./Hero'),{ssr:false});
const smooth=(a:number,b:number,x:number)=>{const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)};
export default function HeroSequence(){const ref=useRef<HTMLElement>(null);
 useEffect(()=>{const el=ref.current;if(!el)return;const preference=matchMedia('(prefers-reduced-motion: reduce)');let frame=0,previous=0,progress=0;const start=performance.now();let visible=true;
 const update=(now:number)=>{const dt=Math.min((now-previous)/1000,.06)||.016;previous=now;const reduced=preference.matches||innerWidth<=800;const rect=el.getBoundingClientRect();const target=Math.max(0,Math.min(1,-rect.top/Math.max(1,el.offsetHeight-innerHeight)));progress+=(target-progress)*(1-Math.exp(-dt*8));const intro=reduced?1:smooth(.65,1.8,(now-start)/1000);const identity=reduced?1:Math.max(intro*.96,smooth(.05,.2,progress));const heading=1,description=1,actions=1;el.dataset.enhanced=reduced?'false':'true';el.dataset.progress=String(progress);el.dataset.sceneProgress=String(Math.max(progress,intro*.22));el.style.setProperty('--identity-in',String(identity));el.style.setProperty('--headline-in',String(heading));el.style.setProperty('--description-in',String(description));el.style.setProperty('--actions-in',String(actions));el.style.setProperty('--portrait-depth',`${(1-identity)*70-progress*28}px`);el.style.setProperty('--core-intro',String(smooth(0,.6,(now-start)/1000)));el.querySelectorAll<HTMLElement>('.hero-sequence-actions a').forEach(a=>{a.tabIndex=actions>.8?0:-1});if(visible&&!document.hidden)frame=requestAnimationFrame(update);else frame=0};const schedule=()=>{if(!frame)frame=requestAnimationFrame(update)};const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible)schedule()});io.observe(el);addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.addEventListener('visibilitychange',schedule);preference.addEventListener('change',schedule);schedule();return()=>{cancelAnimationFrame(frame);io.disconnect();removeEventListener('scroll',schedule);removeEventListener('resize',schedule);document.removeEventListener('visibilitychange',schedule);preference.removeEventListener('change',schedule)}},[]);
 return <section id="introduction" className="cinematic-hero" ref={ref} aria-label="Muhammad Luqman portfolio introduction"><div className="hero-sequence-viewport"><div className="hero-sequence-scene"><Core/></div><div className="hero-sequence-topline mono"><span>FULL STACK DEVELOPER</span></div><div className="hero-sequence-content"><div className="hero-sequence-identity"><span className="status"><i/> AVAILABLE FOR SELECT WORK</span><h1>Muhammad Luqman</h1></div><h2 className="hero-sequence-headline">Have a concept?<br/>I build market-ready<br/><em>digital products.</em></h2><p className="hero-sequence-description">I’m Muhammad Luqman, a Full Stack Developer available for remote work. I build complete digital products from interface to infrastructure.</p><ul className="hero-capabilities" aria-label="What I build">{capabilities.map(c=><li key={c}>{c}</li>)}</ul><div className="hero-sequence-actions"><a href="#work" className="button button-white" data-cursor="VIEW_PROJECT();">EXPLORE MY WORK <span>↘</span></a><Link href="/contact" className="button button-outline" data-cursor="connect();">START A PROJECT <span>↗</span></Link></div></div><IdentityCard paused={false}/><div className="hero-sequence-baseline mono"><span>FIG 01 / THE CONNECTED CORE</span><span>Remote Work</span><a href="#expertise">SCROLL TO EXPLORE ↓</a></div><div className="hero-sequence-progress" aria-hidden="true"><span/></div></div></section>
}

