'use client';
import {useEffect,useRef} from 'react';
import {brainParticles,portraitBounds} from './brainParticles';
const smooth=(a:number,b:number,x:number)=>{const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)};
export default function HeroFallback({reason}:{reason:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current,host=canvas?.closest<HTMLElement>('.cinematic-hero');if(!canvas||!host)return;const ctx=canvas.getContext('2d');if(!ctx)return;const mobile=innerWidth<700,count=mobile?650:1200;const model=brainParticles(count);const points=Array.from({length:count},(_,i)=>({cx:model.core[i*3],cy:model.core[i*3+1],cz:model.core[i*3+2],nx:model.nerve[i*3],ny:model.nerve[i*3+1],nz:model.nerve[i*3+2],sx:model.scatter[i*3],sy:model.scatter[i*3+1],sz:model.scatter[i*3+2],seed:model.seeds[i*4],size:model.seeds[i*4+1]*90,color:model.seeds[i*4+2],isNerve:model.seeds[i*4+3]>.72,x:0,y:0,z:0,influence:0}));
 let width=1,height=1,time=0,previous=0,frame=0,visible=true,progress=0,px=-10,py=-10,tx=-10,ty=-10,dirty=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const resize=()=>{const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const dpr=Math.min(devicePixelRatio,mobile?1:1.5);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);dirty=true};const move=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();tx=e.clientX-r.left;ty=e.clientY-r.top;dirty=true};const leave=()=>{tx=-10;ty=-10;dirty=true};
 const render=(now:number)=>{if(visible&&!document.hidden&&(now-previous>=32||dirty)){const dt=Math.min((now-previous)/1000,.06)||.016;previous=now;const active=!reduced.matches&&host.dataset.paused!=='true';if(active)time+=dt;const target=reduced.matches?.28:parseFloat(host.dataset.sceneProgress||'0');progress+=(target-progress)*(1-Math.exp(-dt*8));px+=(tx-px)*(1-Math.exp(-dt*6));py+=(ty-py)*(1-Math.exp(-dt*6));if(active||dirty||Math.abs(progress-target)>.001){dirty=false;ctx.clearRect(0,0,width,height);const branch=smooth(.05,.35,progress),dissolve=smooth(.58,1,progress),pan=smooth(.08,.34,progress),scale=height*.245;
 for(const p of points){const flow=p.isNerve?branch:0;let x=p.cx+(p.nx-p.cx)*flow,y=p.cy+(p.ny-p.cy)*flow,z=p.cz+(p.nz-p.cz)*flow;x+=(p.sx-x)*dissolve*.85;y+=(p.sy-y)*dissolve*.85;z+=(p.sz-z)*dissolve*.85;x+=Math.sin(time*.3+p.seed*15)*.025;y+=Math.cos(time*.25+p.seed*19)*.025;const a=.15+progress*.75+Math.sin(time*.1)*.045,xr=x*Math.cos(a)+z*Math.sin(a),zr=-x*Math.sin(a)+z*Math.cos(a),perspective=5.9/(5.9-zr);p.x=width*.5+(xr+pan*(mobile?0:.65))*scale*perspective;p.y=height*.5-(y-pan*.08)*scale*perspective;p.z=zr;const targetInfluence=active?Math.max(0,1-Math.hypot(p.x-px,p.y-py)/(height*.16))**2:0;p.influence+=(targetInfluence-p.influence)*(1-Math.exp(-dt*6))}
 points.sort((a,b)=>a.z-b.z);const bounds=portraitBounds(host,canvas);
 ctx.save();if(bounds){ctx.beginPath();ctx.rect(0,0,width,height);ctx.rect(bounds.left-14,bounds.top-14,bounds.right-bounds.left+28,bounds.bottom-bounds.top+28);ctx.clip('evenodd')}ctx.strokeStyle='#91c8da';ctx.lineWidth=.8;ctx.globalAlpha=.22*(1-dissolve);
 const angle=.15+progress*.75+Math.sin(time*.1)*.045;
 for(const side of [-1,1])for(let fold=0;fold<9;fold++){ctx.beginPath();for(let j=0;j<=60;j++){const theta=j/60*Math.PI,phi=fold/9*Math.PI*2+.11*Math.sin(theta*9+fold),ridge=1+.05*Math.sin(theta*15+phi*6),x=side*(.1+Math.abs(Math.cos(phi))*Math.sin(theta)*.8)*ridge*1.2,y=Math.cos(theta)*.72+.08,z=Math.sin(phi)*Math.sin(theta)*.68;const xr=x*Math.cos(angle)+z*Math.sin(angle),zr=-x*Math.sin(angle)+z*Math.cos(angle),perspective=5.9/(5.9-zr),sx=width*.5+(xr+pan*(mobile?0:.65))*scale*perspective,sy=height*.5-(y-pan*.08)*scale*perspective;if(j===0)ctx.moveTo(sx,sy);else ctx.lineTo(sx,sy)}ctx.stroke()}ctx.restore();
 for(const p of points){if(bounds&&p.x>bounds.left-14&&p.x<bounds.right+14&&p.y>bounds.top-14&&p.y<bounds.bottom+14)continue;const size=p.size*(1+p.influence*2.4)*(1+p.z*.12)*(mobile?.8:1),a=p.seed*23+time*(.04+p.seed*.07),c=Math.cos(a),s=Math.sin(a);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.globalAlpha=(.32+(p.z+.6)*.16+(p.isNerve?Math.sin(time*1.3+p.seed*16)*.1:0))*(1-dissolve*.4)*(1-pan*.9*(1-smooth(width*.43,width*.56,p.x))); const colors=p.color<.66?['#e0dfed','#8e8ca6','#b6b4c6']:p.color<.81?['#80caff','#246498','#4a9ed7']:p.color<.93?['#dabf8b','#8c663a','#b98f56']:['#7af3b5','#248160','#46c68c'];ctx.fillStyle=colors[0];ctx.beginPath();ctx.moveTo(0,-size*1.6);ctx.lineTo(size*(.9+Math.abs(c)*.4),size*.5);ctx.lineTo(-size*.12,0);ctx.closePath();ctx.fill();ctx.fillStyle=colors[1];ctx.beginPath();ctx.moveTo(0,-size*1.6);ctx.lineTo(-size*(.8+Math.abs(s)*.4),size*.65);ctx.lineTo(-size*.12,0);ctx.closePath();ctx.fill();ctx.fillStyle=colors[2];ctx.beginPath();ctx.moveTo(-size*(.8+Math.abs(s)*.4),size*.65);ctx.lineTo(size*(.9+Math.abs(c)*.4),size*.5);ctx.lineTo(-size*.12,0);ctx.closePath();ctx.fill();ctx.restore()}ctx.globalAlpha=1;canvas.dataset.ready='true'}}frame=requestAnimationFrame(render)};
 const ro=new ResizeObserver(resize);ro.observe(canvas);const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;dirty=true});io.observe(host);host.addEventListener('pointermove',move,{passive:true});host.addEventListener('pointerleave',leave);resize();frame=requestAnimationFrame(render);return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();host.removeEventListener('pointermove',move);host.removeEventListener('pointerleave',leave)}},[]);return <canvas ref={ref} className="hero-fallback-canvas" data-reason={reason} aria-hidden="true"/>}
