'use client';
import Link from 'next/link';
import {useState,type PointerEvent} from 'react';
import {usePathname} from 'next/navigation';
export default function Navigation(){
 const [open,setOpen]=useState(false);const pathname=usePathname();
 const move=(e:PointerEvent<HTMLAnchorElement>)=>{if(e.pointerType!=='mouse'||!matchMedia('(hover:hover) and (pointer:fine)').matches||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect(),x=Math.max(-1,Math.min(1,(e.clientX-r.left)/r.width*2-1)),y=Math.max(-1,Math.min(1,(e.clientY-r.top)/r.height*2-1));e.currentTarget.style.setProperty('--nav-x',`${x*3}px`);e.currentTarget.style.setProperty('--nav-y',`${y*3}px`)};
 const reset=(e:PointerEvent<HTMLAnchorElement>)=>{e.currentTarget.style.removeProperty('--nav-x');e.currentTarget.style.removeProperty('--nav-y')};
 return <header className="site-header portfolio-navigation"><div className="nav-signal-field" aria-hidden="true">{Array.from({length:9},(_,i)=><i key={i} style={{left:`${8+i*10}%`,top:`${20+(i%3)*25}%`,animationDelay:`${-i*1.7}s`}}/>)}</div><Link className="brand" href="/" aria-label="Muhammad Luqman home">ML<span className="brand-slash">/</span><span className="brand-name">MUHAMMAD<br/>LUQMAN</span></Link><button className="menu-toggle" aria-expanded={open} aria-controls="main-navigation" onClick={()=>setOpen(!open)}>{open?'CLOSE −':'MENU +'}</button><nav id="main-navigation" className={open?'nav open':'nav'} aria-label="Main navigation">{[['Work','/work'],['About','/about'],['Services','/services'],['Guides','/guides']].map(([label,href])=><Link className="nav-control" onPointerMove={move} onPointerLeave={reset} onPointerCancel={reset} onClick={()=>setOpen(false)} href={href} key={label} aria-current={pathname===href||pathname.startsWith(`${href}/`)?'page':undefined}><span>{label}<i aria-hidden="true">↗</i></span></Link>)}<Link onClick={()=>setOpen(false)} href="/contact" className="nav-cta" data-cursor="connect();">LET’S TALK <span>↗</span></Link></nav></header>
}
