'use client';
import {useEffect,useRef,useState} from 'react';
const steps=[
 {title:'Discover',copy:'Understand the user, the objective and the technical constraints.',tag:'IDEA / PLAN',color:'#24ff8a'},
 {title:'Structure',copy:'Turn the idea into a clear architecture and release plan.',tag:'ARCHITECTURE',color:'#548fff'},
 {title:'Design',copy:'Build a visual system that is intuitive, distinctive and responsive.',tag:'INTERFACE',color:'#ff9a4a'},
 {title:'Engineer',copy:'Connect frontend, application logic, APIs and data.',tag:'BUILD / CONNECT',color:'#24ffbb'},
 {title:'Validate',copy:'Test real interactions, edge cases and performance.',tag:'TEST',color:'#ffac67'},
 {title:'Launch',copy:'Deploy confidently and continue improving the product using real feedback.',tag:'DEPLOY / ITERATE',color:'#a8edff'},
];
export default function ProcessJourney(){
 const ref=useRef<HTMLDivElement>(null);const [active,setActive]=useState(0),[paused,setPaused]=useState(false);
 useEffect(()=>{const el=ref.current;if(!el)return;const preference=matchMedia('(prefers-reduced-motion: reduce)');let frame=0,last=-1;const update=()=>{frame=0;if(preference.matches||innerHeight<=700){el.dataset.enhanced='false';return}const rect=el.getBoundingClientRect(),travel=el.offsetHeight-innerHeight;const progress=Math.max(0,Math.min(1,(100-rect.top)/Math.max(1,travel)));const value=progress*5,index=Math.min(5,Math.floor(value+.2));el.dataset.enhanced='true';el.style.setProperty('--journey-progress',String(progress));el.style.setProperty('--planet-rise',String(Math.min(1,progress*12)));el.style.setProperty('--planet-turn',`${progress*120}deg`);el.style.setProperty('--stage-color',steps[index].color);if(last!==index){last=index;setActive(index)}};const schedule=()=>{if(!frame)frame=requestAnimationFrame(update)};addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);preference.addEventListener('change',schedule);update();return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',schedule);removeEventListener('resize',schedule);preference.removeEventListener('change',schedule)}},[]);
 const go=(index:number)=>{const el=ref.current;if(!el)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches||innerHeight<=700;if(reduced){el.querySelectorAll('article')[index]?.scrollIntoView({block:'center'});return}const travel=el.offsetHeight-innerHeight;window.scrollTo({top:scrollY+el.getBoundingClientRect().top-100+(index/5)*travel,behavior:'smooth'})};
 return <div className="process-journey" ref={ref} data-paused={paused}><div className="journey-viewport"><div className="journey-stars" aria-hidden="true"/><div className="journey-top"><span className="pipeline-status mono"><i/> PIPELINE: ACTIVE</span><button className="journey-pause mono" onClick={()=>setPaused(v=>!v)} aria-pressed={paused}>{paused?'RESUME ROTATION':'PAUSE ROTATION'}</button></div><div className="journey-intro"><h2>Good products<br/>don’t happen<br/>by accident.</h2><p>A clear process. Connected decisions.<br/>A product that’s ready for the real world.</p></div><div className="process-planet-scene" aria-hidden="true"><div className="process-orbit orbit-one"/><div className="process-orbit orbit-two"/><div className="satellite satellite-one"/><div className="satellite satellite-two"/><div className="process-planet"><div className="planet-surface"><svg viewBox="0 0 800 400" preserveAspectRatio="none"><defs><pattern id="terrain-pattern" width="400" height="400" patternUnits="userSpaceOnUse"><path d="M12 68L75 25 117 49 158 31 191 77 145 118 151 154 106 192 113 239 77 277 51 241 65 193 30 145Z M245 39L291 70 356 67 382 110 325 155 301 187 327 211 293 255 255 241 233 286 192 271 202 225 221 180 198 151 225 98Z M308 309L365 289 396 325 356 365 321 354Z" fill="currentColor" opacity=".7"/><path d="M0 90Q100 35 200 85T400 90M0 230Q100 180 200 231T400 230M0 300Q100 249 200 297T400 300" fill="none" stroke="white" strokeWidth="9" opacity=".13"/></pattern></defs><rect width="800" height="400" fill="url(#terrain-pattern)"/></svg></div><div className="planet-shading"/><div className="planet-grid"/></div><span className="planet-caption mono">PRODUCTION SYSTEM / 0{active+1}</span></div><div className="journey-stage-list">{steps.map((step,i)=><article className={`journey-stage ${active===i?'is-active':''}`} key={step.title} aria-current={active===i?'step':undefined}><span className="journey-stage-tag mono">0{i+1} <b>{step.tag}</b></span><h3>{step.title}</h3><p>{step.copy}</p><span className="journey-stage-rule"/></article>)}</div><nav className="journey-stage-nav" aria-label="Development process stages">{steps.map((s,i)=><button key={s.title} onClick={()=>go(i)} aria-current={active===i?'step':undefined}><span>0{i+1}</span><strong>{s.title}</strong></button>)}</nav><div className="journey-progress" aria-hidden="true"><span/></div><span className="journey-scroll mono">SCROLL TO ADVANCE ↓</span></div></div>
}
