import {Label} from './Sections';
const references=[
 ['Meridian','Market intelligence, strategy analysis and historical replay.','Meridian','https://trader-arc.vercel.app'],
 ['Resolve','Outcome-based missions, escrow workflows and verified payouts.','Things-to-do','https://resolve-self.vercel.app'],
 ['RepoDiet','Repository cleanup with independent verification and reviewable pull requests.','agentPass','https://skillswap-virid-kappa.vercel.app'],
 ['RepoDiet / E2E Fixture','A controlled test repository for evaluating cleanup accuracy.','repodiet-e2e-test',null],
 ['Jhon Mix / Portfolio','A responsive portfolio template built with HTML, CSS and JavaScript.','bshg',null],
 ['rusd','Repository listed publicly; no implementation is currently published.','rusd',null],
 ['For-Mints','Repository listed publicly; no implementation is currently published.','For-Mints',null],
];
export default function ProjectCollection(){return <><section className="current-project section"><Label number="WIP">CURRENTLY BUILDING</Label><a className="xroga-card reveal" href="https://xroga.com/" target="_blank" rel="noreferrer" data-tilt><div><span className="status"><i/> WORK IN PROGRESS</span><h2>Xroga<span>↗</span></h2><p>An AI app builder that builds, tests and ships code you own.</p><span className="text-link">EXPLORE XROGA ↗</span></div><div className="xroga-terminal" aria-hidden="true"><span>PRODUCT / XROGA</span><p><b>01</b> idea → application</p><p><b>02</b> build → test</p><p><b>03</b> code → ship</p><span className="terminal-signal">● CURRENT DEVELOPMENT</span></div></a></section><section className="reference-work section"><Label number="SRC">OPEN-SOURCE PROJECT COLLECTION</Label><div className="section-heading reveal"><h2>Builds worth<br/>exploring.</h2><p>Projects from <a href="https://github.com/mabdullah-built" target="_blank" rel="noreferrer">Muhammad Abdullah / mabdullah-built ↗</a>.<br/>Credited to their original author; included as references.</p></div><div className="reference-grid">{references.map(([title,copy,repo,live],i)=><article className="reference-card reveal" key={repo}><span className="mono">SOURCE / 0{i+1}</span><h3>{title}</h3><p>{copy}</p><span className="source-credit">Original source: mabdullah-built</span><div className="project-links"><a href={`https://github.com/mabdullah-built/${repo}`} target="_blank" rel="noreferrer">VIEW CODE ↗</a>{live&&<a href={live} target="_blank" rel="noreferrer">VIEW LIVE ↗</a>}</div></article>)}</div></section></>}
