import Link from 'next/link';
import WorkGallery from './WorkGallery';
import ServiceShowcase from './ServiceShowcase';
import {email,github} from './data';
import ArchitectureFlow from './ArchitectureFlow';
import ContactForm from './ContactForm';
import {Bot} from './ContactBot';
import ProcessJourney from './ProcessJourney';
export function Label({number,children}:{number:string;children:React.ReactNode}){return <div className="section-label"><span className="section-index">{number}</span><span>{children}</span><span className="label-line"/></div>}
export function Work(){return <WorkGallery/>}
export function About(){return <section className="about section" id="about"><Label number="03">HUMAN BEHIND THE SYSTEM</Label><div className="about-layout"><div className="reveal"><h2>I don’t just<br/>build pages.<br/><span>I build the<br/>system behind<br/>them.</span></h2><div className="signature">Muhammad Luqman <span>↗</span></div></div><div className="about-copy reveal"><div className="about-symbol" aria-hidden="true">&lt;<span>/</span>&gt;</div><p>I’m Muhammad Luqman, a <strong>Full Stack Developer based in Faisalabad, Punjab, Pakistan</strong>. I build digital products as connected systems, bringing product thinking, interface design, frontend engineering, backend logic, APIs, data, automation and deployment together.</p><p>I start by understanding what a user needs to accomplish, then shape the product structure, interaction flow and technical architecture around that goal. The result should be intuitive at the surface and dependable underneath.</p><p>My focus is <strong>clarity, performance, maintainability and real-world usability</strong>, from a custom website or MVP to a SaaS platform, AI-enabled system, automation or Web3 product.</p><Link href="/contact" className="text-link">LET’S BUILD SOMETHING THAT WORKS <span>↗</span></Link></div></div><div className="about-principles"><span>PRODUCT THINKING</span><span>PROBLEM SOLVING</span><span>ENGINEERING WITH INTENT</span></div></section>}
export function Expertise(){return <section className="expertise section" id="expertise"><Label number="04">SYSTEM ARCHITECTURE</Label><div className="section-heading reveal"><h2>One product.<br/>Every layer.</h2><p>The interface is only the beginning.<br/>I connect the complete system.</p></div><ArchitectureFlow/></section>}
export function Process(){return <section className="process process-solar section" id="process"><Label number="05">FROM IDEA TO PRODUCTION</Label><ProcessJourney/></section>}
export function Services(){return <ServiceShowcase/>}
export function Contact(){return <section className="contact section" id="contact"><Label number="07">START A TRANSMISSION</Label><div className="contact-heading reveal"><a href="#project-enquiry" className="contact-mascot" aria-label="Contact Us — open project enquiry"><Bot/><span>Contact Us ↗</span></a><div className="status"><i/> AVAILABLE FOR SELECT PROJECTS</div><h2>Have an idea?<br/>Let’s build<br/><span>what’s next.</span><sup>↗</sup></h2></div><div className="contact-layout"><div className="contact-copy"><p>Tell me what you are building, what stage it is currently at and what you need the product to achieve. Whether it is a new idea, an unfinished application or a difficult feature, let’s turn it into something real.</p><a href={`mailto:${email}`} className="email-link">{email}<span>↗</span></a><div className="social-links"><a href={github} target="_blank" rel="noreferrer" data-cursor="git push">GITHUB ↗</a><a href={`mailto:${email}?subject=Discovery%20call%20request`}>REQUEST A CALL ↗</a></div></div><ContactForm/></div></section>}
