import Link from 'next/link';
import WorkGallery from './WorkGallery';
import {expertise,services,email,github} from './data';
import ContactForm from './ContactForm';
import {Bot} from './ContactBot';
import ProcessJourney from './ProcessJourney';
export function Label({number,children}:{number:string;children:React.ReactNode}){return <div className="section-label"><span className="section-index">{number}</span><span>{children}</span><span className="label-line"/></div>}
export function Work(){return <WorkGallery/>}
export function About(){return <section className="about section" id="about"><Label number="03">HUMAN BEHIND THE SYSTEM</Label><div className="about-layout"><div className="reveal"><h2>I don’t just<br/>build pages.<br/><span>I build the<br/>system behind<br/>them.</span></h2><div className="signature">Muhammad Luqman <span>↗</span></div></div><div className="about-copy reveal"><div className="about-symbol" aria-hidden="true">&lt;<span>/</span>&gt;</div><p>I’m Muhammad Luqman, a <strong>full-stack developer</strong> who enjoys working where design, logic and real-world functionality meet. My goal is not simply to make interfaces look polished; it is to make the complete product feel coherent—from the first interaction to the database and deployment behind it.</p><p>I approach projects by understanding what the user actually needs to accomplish, simplifying the path to that outcome, and then engineering the <strong>frontend, backend and integrations</strong> as one connected product.</p><p>Whether I’m developing a new digital product, improving an existing application or building a complex feature, I focus on <strong>clarity, performance, maintainability</strong> and a strong user experience.</p><Link href="/contact" className="text-link">LET’S BUILD SOMETHING THAT WORKS <span>↗</span></Link></div></div><div className="about-principles"><span>PRODUCT THINKING</span><span>PROBLEM SOLVING</span><span>ENGINEERING WITH INTENT</span></div></section>}
export function Expertise(){return <section className="expertise section" id="expertise"><Label number="04">SYSTEM ARCHITECTURE</Label><div className="section-heading reveal"><h2>One product.<br/>Every layer.</h2><p>The interface is only the beginning.<br/>I connect the complete system.</p></div><div className="architecture"><div className="architecture-core"><span className="mono">ENGINEERING CORE</span><strong>LUQMAN<span>.DEV</span></strong><div className="core-lines"><span>FRONTEND</span><span>BACKEND</span><span>DATA</span><span>AI</span><span>INFRASTRUCTURE</span></div></div><div className="expertise-grid">{expertise.map(([title,description,n])=><article className="expertise-item reveal" key={title} tabIndex={0}><span className="mono">LAYER / {n}</span><h3>{title}<span>↗</span></h3><p>{description}</p><div className="architecture-signal"/></article>)}</div></div></section>}
export function Process(){return <section className="process process-solar section" id="process"><Label number="05">FROM IDEA TO PRODUCTION</Label><ProcessJourney/></section>}
export function Services(){return <section className="services section" id="services"><Label number="06">WHAT I CAN BUILD</Label><div className="section-heading reveal"><h2>Your next idea.<br/><span className="outline-text">My next build.</span></h2><p>Focused capabilities for products<br/>that need to work beautifully.</p></div><div className="services-grid">{services.map(([title,description,n])=><Link className="service-card reveal" href={`/contact?type=${encodeURIComponent(title)}`} key={title}><div className="service-top mono"><span>MODULE_{n}</span><span>↗</span></div><h3>{title}</h3><p>{description}</p><div className="compile-status mono"><span className="compile-idle">&lt;ready to build /&gt;</span><span className="compile-active">DEPENDENCIES OK <b>STATUS: READY</b></span></div></Link>)}</div></section>}
export function Journey(){return <section className="journey section"><Label number="07">THE BUILD LOG</Label><div className="journey-layout"><h2>Always<br/><span className="outline-text">in progress.</span></h2><div className="commit-log">{[['NOW','feat: building connected products','Full-stack engineering, thoughtful interfaces and practical automation.'],['BUILD','build: connect every layer','The Circle repositories connect market data, application logic, APIs and cross-chain integrations.'],['ITERATE','refactor: improve the experience','Inspect the implementation, identify friction and make the next version better.'],['NEXT','learn: never stop','Better systems. Clearer decisions. Stronger products.']].map(([tag,title,copy])=><article className="commit reveal" key={tag}><span className="commit-dot"/><span className="mono commit-tag">{tag}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>}
export function Contact(){return <section className="contact section" id="contact"><Label number="08">START A TRANSMISSION</Label><div className="contact-heading reveal"><a href="#project-enquiry" className="contact-mascot" aria-label="Contact Us — open project enquiry"><Bot/><span>Contact Us ↗</span></a><div className="status"><i/> AVAILABLE FOR SELECT PROJECTS</div><h2>Have an idea?<br/>Let’s build<br/><span>what’s next.</span><sup>↗</sup></h2></div><div className="contact-layout"><div className="contact-copy"><p>Tell me what you are building, what stage it is currently at and what you need the product to achieve. Whether it is a new idea, an unfinished application or a difficult feature, let’s turn it into something real.</p><a href={`mailto:${email}`} className="email-link">{email}<span>↗</span></a><div className="social-links"><a href={github} target="_blank" rel="noreferrer" data-cursor="git push">GITHUB ↗</a><a href={`mailto:${email}?subject=Discovery%20call%20request`}>REQUEST A CALL ↗</a></div></div><ContactForm/></div></section>}
