'use client';
import {useEffect,useRef} from 'react';
import * as T from 'three';
import {writeServiceForm} from './servicesGeometry';
export default function ServicesVisual(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{
 const canvas=ref.current,host=canvas?.closest<HTMLElement>('.services-experience');if(!canvas||!host)return;const mobile=innerWidth<700,segments=mobile?52:84,rows=mobile?3:5,bands=mobile?4:6,positions=new Float32Array(bands*(segments+1)*(rows+1)*3);const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(positions,3).setUsage(T.DynamicDrawUsage));const indices:number[]=[];for(let b=0;b<bands;b++)for(let i=0;i<segments;i++)for(let j=0;j<rows;j++){const a=b*(segments+1)*(rows+1)+i*(rows+1)+j,c=a+rows+1;indices.push(a,c,a+1,a+1,c,c+1)}geometry.setIndex(indices);
 let renderer:T.WebGLRenderer|null=null;const gl=canvas.getContext('webgl2',{alpha:true,antialias:true});const ctx=gl?null:canvas.getContext('2d');const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,30),group=new T.Group();scene.add(group);const material=new T.MeshStandardMaterial({color:0x153d0a,emissive:0x63ef17,emissiveIntensity:.19,metalness:.65,roughness:.4,side:T.DoubleSide});const wireMaterial=new T.MeshBasicMaterial({color:0x77ff20,wireframe:true,transparent:true,opacity:.09,depthWrite:false});group.add(new T.Mesh(geometry,material),new T.Mesh(geometry,wireMaterial));scene.add(new T.HemisphereLight(0xaccf81,0x020403,1.1));const key=new T.PointLight(0x8cff32,18,15);key.position.set(-2,3,3);scene.add(key);const rim=new T.PointLight(0x63ef17,10,12);rim.position.set(3,-1,-2);scene.add(rim);
 if(gl)try{renderer=new T.WebGLRenderer({canvas,context:gl,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.5));renderer.toneMapping=T.ACESFilmicToneMapping}catch{gl.getExtension('WEBGL_lose_context')?.loseContext()}
 let width=1,height=1,frame=0,last=0,time=0,phase=0,px=0,py=0,influence=0,visible=false;const projected=new Float32Array(positions.length);const resize=()=>{const r=canvas.getBoundingClientRect();width=r.width;height=r.height;if(renderer){renderer.setSize(width,height,false);camera.aspect=width/height;camera.position.set(0,0,mobile?6:5.2);camera.updateProjectionMatrix()}else if(ctx){const dpr=Math.min(devicePixelRatio,mobile?1:1.5);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}};
 const fallback=()=>{if(!ctx)return;ctx.clearRect(0,0,width,height);const angle=.28+phase*.17+px*.025,ca=Math.cos(angle),sa=Math.sin(angle),scale=Math.min(width*.31,height*.43);for(let k=0;k<positions.length;k+=3){const x=positions[k],y=positions[k+1],z=positions[k+2],xx=x*ca+z*sa,zz=-x*sa+z*ca,p=5/(5-zz);projected[k]=width*.5+xx*scale*p;projected[k+1]=height*.5-y*scale*p;projected[k+2]=zz}ctx.lineWidth=.6;for(let b=0;b<bands;b++)for(let i=0;i<segments;i++){const a=(b*(segments+1)*(rows+1)+i*(rows+1))*3,c=a+(rows+1)*3,d=c+rows*3,e=a+rows*3,energy=(Math.sin(i/segments*Math.PI*4-time*.7+b)+1)/2;ctx.beginPath();ctx.moveTo(projected[a],projected[a+1]);ctx.lineTo(projected[c],projected[c+1]);ctx.lineTo(projected[d],projected[d+1]);ctx.lineTo(projected[e],projected[e+1]);ctx.closePath();ctx.fillStyle=`rgba(41,${Math.round(85+energy*105)},12,${.1+energy*.14+influence*.015})`;ctx.fill();ctx.strokeStyle=`rgba(119,255,32,${.12+energy*.4})`;ctx.stroke()}for(let b=0;b<bands;b++){ctx.beginPath();for(let i=0;i<=segments;i++){const k=(b*(segments+1)*(rows+1)+i*(rows+1))*3;i===0?ctx.moveTo(projected[k],projected[k+1]):ctx.lineTo(projected[k],projected[k+1])}ctx.strokeStyle='#77ff20';ctx.globalAlpha=.5;ctx.lineWidth=1.2;ctx.stroke();ctx.globalAlpha=1}};
 const render=(now:number)=>{frame=0;if(!visible||document.hidden)return;if(now-last>=33){const dt=Math.min((now-last)/1000,.06)||.016;last=now;const reduced=host.dataset.reduced==='true',paused=host.dataset.paused==='true',moving=!reduced&&!paused,damp=1-Math.exp(-dt*7);if(moving)time+=dt;phase+=((reduced?0:Number(host.dataset.phase||0))-phase)*damp;px+=((moving?Number(host.dataset.pointerX||0):0)-px)*damp;py+=((moving?Number(host.dataset.pointerY||0):0)-py)*damp;influence+=((moving&&Number(host.dataset.hover??-1)>=0?1:0)-influence)*damp;writeServiceForm(positions,segments,rows,bands,phase,time,influence,Number(host.dataset.hover??-1));if(renderer){geometry.attributes.position.needsUpdate=true;geometry.computeVertexNormals();group.rotation.set(py*.025,.28+phase*.17+px*.035,Math.sin(time*.13)*.03);material.emissiveIntensity=.16+influence*.035+Math.sin(time*.3)*.02;renderer.render(scene,camera)}else fallback();canvas.dataset.ready='true';canvas.dataset.renderer=renderer?'webgl':'canvas';}frame=requestAnimationFrame(render)};
 const schedule=()=>{if(!frame)frame=requestAnimationFrame(render)};const ro=new ResizeObserver(resize);ro.observe(canvas);const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible)schedule()});io.observe(canvas);document.addEventListener('visibilitychange',schedule);const lost=(e:Event)=>{e.preventDefault();canvas.dataset.renderer='unavailable'};canvas.addEventListener('webglcontextlost',lost);resize();return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();document.removeEventListener('visibilitychange',schedule);canvas.removeEventListener('webglcontextlost',lost);renderer?.dispose();geometry.dispose();material.dispose();wireMaterial.dispose()};
 },[]);return <canvas ref={ref} className="services-form-canvas" aria-hidden="true"/>}
