'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import dynamic from 'next/dynamic';
const Visual=dynamic(()=>import('./ServicesVisual'),{ssr:false});
export default function ServiceJourney({children}:{children:ReactNode}){
 const ref=useRef<HTMLDivElement>(null);const [near,setNear]=useState(false),[paused,setPaused]=useState(false);
 useEffect(()=>{const host=ref.current;if(!host)return;const modules=Array.from(host.querySelectorAll<HTMLElement>('.fluid-module'));const reduce=matchMedia('(prefers-reduced-motion: reduce)');let frame=0,last=0,phase=0,visible=false;
 const update=(now:number)=>{frame=0;if(!visible||document.hidden)return;const dt=Math.min((now-last)/1000,.05)||.016;last=now;let nearest=0,distance=Infinity;modules.forEach((module,i)=>{const r=module.getBoundingClientRect(),d=Math.abs(r.top+r.height*.5-innerHeight*.53);if(d<distance){distance=d;nearest=i}});const rect=host.getBoundingClientRect(),travel=Math.max(1,rect.height-innerHeight*.4),target=reduce.matches?0:Math.max(0,Math.min(5,(innerHeight*.5-rect.top)/travel*5));phase+=(target-phase)*(1-Math.exp(-dt*8));host.dataset.phase=String(phase);host.dataset.reduced=String(reduce.matches);modules.forEach((module,i)=>module.dataset.active=String(i===nearest));if(!reduce.matches)frame=requestAnimationFrame(update)};
 const schedule=()=>{if(!frame)frame=requestAnimationFrame(update)};const move=(e:PointerEvent)=>{if(e.pointerType==='touch'||reduce.matches)return;const r=host.getBoundingClientRect();host.dataset.pointerX=String((e.clientX-r.left)/r.width*2-1);host.dataset.pointerY=String(e.clientY/innerHeight*2-1)};const reset=()=>{host.dataset.pointerX='0';host.dataset.pointerY='0';host.dataset.hover='-1'};const hover=(e:Event)=>{const node=e.target as HTMLElement;const module=node.closest<HTMLElement>('[data-service-index]');host.dataset.hover=module?.dataset.serviceIndex||'-1'};
 const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible){setNear(true);schedule()}},{rootMargin:'350px'});io.observe(host);host.addEventListener('pointermove',move,{passive:true});host.addEventListener('pointerover',hover);host.addEventListener('pointerleave',reset);host.addEventListener('focusin',hover);host.addEventListener('focusout',reset);addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.addEventListener('visibilitychange',schedule);reduce.addEventListener('change',schedule);return()=>{cancelAnimationFrame(frame);io.disconnect();host.removeEventListener('pointermove',move);host.removeEventListener('pointerover',hover);host.removeEventListener('pointerleave',reset);host.removeEventListener('focusin',hover);host.removeEventListener('focusout',reset);removeEventListener('scroll',schedule);removeEventListener('resize',schedule);document.removeEventListener('visibilitychange',schedule);reduce.removeEventListener('change',schedule)};
 },[]);
 return <div className="services-experience" ref={ref} data-paused={paused}><div className="fluid-stage" aria-hidden="true">{near&&<Visual/>}<div className="fluid-readability"/></div><div className="fluid-controls mono"><span>ONE CONNECTED SYSTEM / SIX CAPABILITIES</span><button onClick={()=>setPaused(v=>!v)} aria-pressed={paused}>{paused?'RESUME SERVICE MOTION':'PAUSE SERVICE MOTION'}</button></div>{children}<div className="fluid-endnote mono"><span>IDEA → ENGINEER → SHIP</span><span>DEPENDENCIES OK / STATUS: READY</span></div></div>
}
