import Image from 'next/image';
import Link from 'next/link';
import {projects} from './data';
import {referenceProjects} from './ProjectCollection';

type Entry={name:string;description:string;category:string;status:string;repo?:string;live?:string|null;image?:string;slug?:string;tags:readonly string[]};
const entries:Entry[]=[
 ...projects.map(p=>({...p,status:'COMPLETED PROJECT'})),
 {name:'Xroga',description:'An AI app builder that builds, tests and ships code you own. Currently working on the product.',category:'AI / PRODUCT DEVELOPMENT',status:'WORK IN PROGRESS',live:'https://xroga.com/',tags:['AI','App builder','Current development']},
 ...referenceProjects.map(([name,description,repo,live])=>({name,description,repo:`https://github.com/mabdullah-built/${repo}`,live,category:'OPEN SOURCE / EXTERNAL REPOSITORY',status:'REFERENCE PROJECT',tags:['Open source','Source available']})),
];
export default function WorkGallery(){return <section className="work section unified-work" id="work"><div className="section-label"><span className="section-index">01</span><span>MY WORK / PROJECT INDEX</span><span className="label-line"/></div><div className="section-heading reveal"><h2>Ideas made<br/><span>operational.</span></h2><p>Completed work. Current development.<br/>One connected project collection.</p></div><div className="work-index">{entries.map((p,i)=><article className="work-entry reveal" key={p.name}><div className="work-entry-visual" data-tilt>{p.image?<Image src={p.image} width={1440} height={960} sizes="(max-width: 800px) 100vw, 45vw" alt={`${p.name} project preview`} className="work-entry-image"/>:<div className={`work-entry-module ${p.status==='WORK IN PROGRESS'?'module-active':''}`} aria-hidden="true"><span className="mono">{p.status==='WORK IN PROGRESS'?'BUILD IN PROGRESS':'REPOSITORY / SOURCE'}</span><strong>{p.name}</strong><div className="module-orbits"><span>&lt;/&gt;</span></div><span className="mono">{p.status==='WORK IN PROGRESS'?'IDEA → BUILD → TEST → SHIP':'EXPLORE → INSPECT → UNDERSTAND'}</span></div>}</div><div className="work-entry-info"><div className="work-entry-meta mono"><span>PROJECT / {String(i+1).padStart(2,'0')}</span><span className={`work-status ${p.status==='WORK IN PROGRESS'?'status-progress':''}`}>{p.status}</span></div><span className="mono work-category">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-links">{p.live&&<a href={p.live} target="_blank" rel="noreferrer" data-cursor="VIEW_PROJECT();">{p.name==='Xroga'?'EXPLORE XROGA':'VIEW LIVE'} ↗</a>}{p.repo&&<a href={p.repo} target="_blank" rel="noreferrer" data-cursor="git push">VIEW CODE ↗</a>}{p.slug&&<Link href={`/work/${p.slug}`}>READ CASE STUDY →</Link>}</div>{p.status==='REFERENCE PROJECT'&&<small className="work-source-note">External open-source reference. Original ownership retained in the linked repository.</small>}</div></article>)}</div></section>}
