import {notFound} from 'next/navigation';
import Link from 'next/link';
import Shell from '../../../components/Shell';
import {Contact} from '../../../components/Sections';
import {articles} from '../../../components/blogData';
import {JsonLd,pageMetadata,siteUrl} from '../../../components/seo';
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)return {title:'Article not found'};const metadata=pageMetadata(`/blog/${slug}`,`${a.title} | Muhammad Luqman`,a.description);return {...metadata,openGraph:{...metadata.openGraph,type:'article',publishedTime:'2026-10-06',authors:['Muhammad Luqman']}}}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)notFound();const url=`${siteUrl}/blog/${slug}`;return <Shell><JsonLd data={{'@context':'https://schema.org','@type':'BlogPosting',headline:a.title,description:a.description,datePublished:'2026-10-06',dateModified:'2026-10-06',author:{'@type':'Person',name:'Muhammad Luqman',url:`${siteUrl}/about`},publisher:{'@id':`${siteUrl}/#person`},mainEntityOfPage:url,url}}/><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:siteUrl},{'@type':'ListItem',position:2,name:'Blog',item:`${siteUrl}/blog`},{'@type':'ListItem',position:3,name:a.title,item:url}]}}/><article className="blog-article"><header className="page-intro"><Link className="mono" href="/blog">ALL ARTICLES ↗</Link><h1>{a.title}</h1><p>{a.description}</p><span className="mono">BY MUHAMMAD LUQMAN · OCTOBER 6, 2026</span></header><div className="blog-body">{a.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<p>Explore <Link href="/work">Muhammad Luqman’s selected work</Link>, read about his <Link href="/services">web development services</Link>, or <Link href="/contact">start a project conversation</Link>.</p></div></article><Contact/></Shell>}
